steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/kubernetes-assignment-453322/k8s-assignment/container1:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/kubernetes-assignment-453322/k8s-assignment/container1:latest']

- name: "gcr.io/cloud-builders/kubectl"
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      gcloud container clusters get-credentials gke-cluster --zone us-central1
      kubectl apply -f pvc.yaml
      kubectl apply -f container1-deployment.yaml
      kubectl apply -f container1-service.yaml

images:
- 'us-central1-docker.pkg.dev/kubernetes-assignment-453322/k8s-assignment/container1:latest'

options:
  logging: CLOUD_LOGGING_ONLY